name: cyberescue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2    
  file_picker: ^5.2.5 # Add this line
  flutter_local_notifications: ^15.0.0
  http: ^0.13.3
  provider: ^6.0.1
  shared_preferences: ^2.1.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  firebase_core_web: ^2.12.0
  firebase_auth_web: ^5.8.13
  google_generative_ai: ^0.0.1-dev # <-- Add this
  
  

# For web support
dependency_overrides:
  js: ^0.6.7



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/ChatBot_Intents/
    - assets/.env



